criticalmaps/criticalmaps-ios

CriticalMass/PLAppDelegate.m, Podfile.lock
I've just fixed the bug with the badge, wich was still visible after opening the app. Then I decreased the uses to 5 and updated the dependencies.
=> Remove badge; Update pods; Decrease uses with 5 until prompt appirater

CriticalMass/PLConstants.m
=> temporary endpoint change

CriticalMass/RuleTableViewCell.xib, CriticalMass/RulesViewController.swift
fixed crash that occured on iOS 10 because of a missing availability check
=> Fixed crash on iOS 10

.travis.yml, CriticalMaps.xcodeproj/project.pbxproj, CriticalMass/ChatViewController.swift, CriticalMass/LocationManager.swift, CriticalMass/TwitterViewController.swift
I updated the Project to Swift 5 and fixed some project warnings 
fixes #57
=> Swift 5 Migration

CriticalMaps.xcodeproj/project.pbxproj, CriticalMass/FormatDisplay.swift, CriticalMass/TweetTableViewCell.swift, CriticalMass/TweetTableViewCell.xib, CriticalMass/TwitterViewController.swift
=> Twitter cell layout fix

CriticalMass/SettingsFooterView.xib
=> Fixed deprecation warning

CriticalMass/MapViewController.swift, CriticalMass/UserTrackingButton.swift
I'm not sure how to reproduce the issue but that hopefully fixes #74
=> fix icon state when leaving following mode

CriticalMass/fr.lproj/InfoPlist.strings, CriticalMass/fr.lproj/Localizable.strings
Hi,
This is my first Pull request, sorry if I made anything wrong. I have no idea how to test the modifications I made but let me know if I can help.
Cheers,
Alban
=> Translation of Localizable.strings in French

CHANGELOG.md, CriticalMaps.xcodeproj/project.pbxproj, CriticalMass/AppController.swift, CriticalMass/NetworkActivityIndicatorHelper.swift, CriticalMass/NetworkOperator.swift, CriticalMass/RequestManager.swift
This will show a small spinner in the statusbar for active network requests
=> Added Network activity indicator support

CriticalMaps.xcodeproj/project.pbxproj, CriticalMass/AppController.swift, CriticalMass/ChatInputView.swift, CriticalMass/ChatNavigationButton.swift, CriticalMass/ChatViewController.swift, CriticalMass/Constants.swift, CriticalMass/MapViewController.swift, CriticalMass/NavigationOverlayViewController.swift, CriticalMass/RulesViewController.swift, CriticalMass/SettingsGithubTableViewCellTableViewCell.swift, CriticalMass/SettingsSection.swift, CriticalMass/SettingsViewController.swift, CriticalMass/String+LocalizedStrings.swift, CriticalMass/TwitterViewController.swift
Intends to collect all NSLocalizedStrings in an extension to make them reusable and remove strings from logic controllers. Also moves and collects all URLs to the Constants container. 
* adds String+LocalizedStrings extension
* update strings in code with static lets from extension
* move URLs in Constants container
* change Constants type to enum so it is not instantiatable
🎨
=> Collect strings

CHANGELOG.md, CriticalMaps.xcodeproj/project.pbxproj, CriticalMass/BlurryOverlayView.swift, CriticalMass/BlurryOverlayView.xib, CriticalMass/ChatMessageTableViewCell.swift, CriticalMass/ChatMessageTableViewCell.xib, CriticalMass/FontMetrics.swift, CriticalMass/Images.xcassets/ArrowButton.imageset/Contents.json, CriticalMass/MapViewController.swift, CriticalMass/MessagesTableViewController.swift, CriticalMass/NoContentMessageLabel.swift, CriticalMass/SettingsGithubTableViewCellTableViewCell.swift, CriticalMass/SettingsGithubTableViewCellTableViewCell.xib, CriticalMass/SettingsInfoTableViewCell.xib, CriticalMass/SettingsSwitchTableViewCell.xib, CriticalMass/ThemeController.swift, CriticalMass/TweetTableViewCell.swift, CriticalMass/TweetTableViewCell.xib, CriticalMass/UIFont+DynamicFont.swift
Adds DynamicType feature to the app.
The app will be more accessable for people with visual impairments when supporting DynamicType.
=> Dynamic type

CriticalMass/fr.lproj/Localizable.strings
Translation based on the English version
Added missing strings
Deleted outdated strings
Improved a few translations
Changed string order and format to match row numbers with the English version
=> Update of French localizable.strings

Settings.bundle/com.mono0926.LicensePlist.latest_result.txt, Settings.bundle/com.mono0926.LicensePlist.plist
=> Updated license-plist

CriticalMaps.xcodeproj/project.pbxproj, CriticalMass/AppController.swift, CriticalMass/AppDataStore.swift, CriticalMass/AppDelegate.swift, CriticalMass/Colors.swift, CriticalMass/DataStore.swift, CriticalMass/FollowFriendsViewController.swift, CriticalMass/FriendSettingsTableViewCell.swift, CriticalMass/FriendSettingsTableViewCell.xib, CriticalMass/FriendTableViewCell.swift, CriticalMass/FriendTableViewCell.xib, CriticalMass/IBConstructable.swift, CriticalMass/ManageFriendsViewController.swift, CriticalMass/ManageFriendsViewController.xib, CriticalMass/QRCodeView.swift, CriticalMass/SettingsSection.swift, CriticalMass/SettingsViewController.swift, CriticalMass/TypeNameProtocol.swift, CriticalMass/UITableView+Register.swift, CriticalMass/UIView+Autolayout.swift, CriticalMassTests/AppDataStoreTests.swift, CriticalMassTests/RequestManagerTests.swift, CriticalMassTests/TestHelper.swift
=> Friends Settings-UI

CriticalMass/AppDataStore.swift, CriticalMass/FollowFriendsViewController.swift, CriticalMass/Friend.swift, CriticalMass/FriendsVerificationController.swift, CriticalMass/Location.swift, CriticalMass/ManageFriendsViewController.swift, CriticalMassTests/AppDataStoreTests.swift, CriticalMassTests/FollowURLObjectTests.swift, CriticalMassTests/FriendsVerificationControllerTests.swift
Please add one or two sentences _why_ this PR was made, and optionally what it adds/changes…
=> Added isOnline to friends; cleanup #Cyclehack

CriticalMass/ChatManager.swift, CriticalMass/IDStore.swift, CriticalMass/ManageFriendsViewController.swift, Settings.bundle/com.mono0926.LicensePlist.plist, Settings.bundle/com.mono0926.LicensePlist/SDWebImage.plist
Please add one or two sentences _why_ this PR was made, and optionally what it adds/changes…
=> Friends dismiss editing on tap #cyclehack

CriticalMass/BikeAnnotationView.swift, CriticalMass/IDStore.swift, CriticalMass/IdentifiableAnnnotation.swift, CriticalMass/MapViewController.swift
=> Friends map ui

CriticalMass/BikeAnnotationView.swift, CriticalMass/FriendsVerificationController.swift, CriticalMass/IdentifiableAnnnotation.swift, CriticalMass/MapViewController.swift
Please add one or two sentences _why_ this PR was made, and optionally what it adds/changes…
=> hacked maps friends connection #cyclehack

CriticalMass/BikeAnnotationView.swift, CriticalMass/ManageFriendsViewController.swift
; disable colliding gesture recognizer in friend view
=> Fix show friends name on map #Cyclehack

CriticalMaps.xcodeproj/project.pbxproj, Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
Updates the Package to use upstream repo as dependency.
=> update textview dependency

CHANGELOG.md, CriticalMaps.xcodeproj/project.pbxproj, CriticalMass/de.lproj/Localizable.strings, CriticalMass/en.lproj/Localizable.strings, CriticalMass/es.lproj/InfoPlist.strings, CriticalMass/es.lproj/Localizable.strings, CriticalMass/fr.lproj/Localizable.strings, CriticalMass/it.lproj/Localizable.strings, CriticalMassTests/es.lproj/InfoPlist.strings
Updates translations and adds spanish translations.
=> update translations and add spanish

CriticalMaps.xcodeproj/project.pbxproj, CriticalMass/AppController.swift, CriticalMass/ChatManager.swift, CriticalMass/ErrorHandler.swift, CriticalMass/Feature.swift, CriticalMass/FollowFriendsViewController.swift, CriticalMass/MapOverlayErrorHandler.swift, CriticalMass/MapViewController.swift, CriticalMass/RequestManager.swift, CriticalMass/TwitterManager.swift, Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
I converted ErrorHandler into a protocol to make it easier to inject different error handler for different use cases and prototyped a MapOverlayErrorHandler (behind a Feature flag)
I'm not super happy with my implementation (especially AppController becomes hard to understand with all the inner dependencies between the lazy variables) would appreciate some feedback!
=> Converted ErrorHandler into a Protocol

CriticalMaps.xcodeproj/project.pbxproj, CriticalMass/Endpoint.swift, CriticalMassTests/TwitterRequestTests.swift
fixed #236 
According to the docs https://developer.apple.com/documentation/foundation/urlcomponents/1780032-url path needs to start with "/" otherwise url returns nil which causes a broken request. This bug only affects the current master branch + test flight build. The store build works
=> Fixed TwitterRequest

CriticalMaps.xcodeproj/project.pbxproj, CriticalMass/AppDataStore.swift, CriticalMass/BikeAnnotationController.swift, CriticalMass/ChatManager.swift, CriticalMass/LocationManager.swift, CriticalMass/ManageFriendsViewController.swift, CriticalMass/MapViewController.swift, CriticalMass/Notification+Static.swift, CriticalMass/Preferences.swift, CriticalMass/ThemeController.swift, CriticalMassTests/AppDataStoreTests.swift, CriticalMassTests/ChatManagerTests.swift
Makes Notification subscribtions etc. easier to read
=> rename extension and update static properties

CriticalMaps.xcodeproj/project.pbxproj, CriticalMass/FormatDisplay.swift, CriticalMass/GCD.swift, Package.swift
Just some minor clean up. 
- Move Extension Files to Extension Folder
- Use default arguments of DateComponent initializer
=> Move Extensions to correct folder

CriticalMass/Feature.swift, CriticalMass/MapViewController.swift
Removes `events` feature flag
To activate the event feature
closes #194
=> remove event feature flag

CriticalMass/CMAnnotationView.swift, CriticalMass/CriticalMassAnnotation.swift, CriticalMass/Ride.swift, CriticalMassTests/NextRideManagerTests.swift, CriticalMassTests/NextRidesRequestTests.swift
Adds small improvements for the event feature and updates the Ride model support updated API. 
* Add KVO support to annotation
* use designated `prepareForDisplay` func of the annotationview
* add new endpoint properties
=> Small event improvement

CriticalMaps.xcodeproj/project.pbxproj
Update Specified Swift Version in Xcode Project
Forgotten on #280
=> Update Swift Version in Xcode

CriticalMass/ChatMessageTableViewCell.xib
Set `ChatMessageTableViewCell` selection style to `.none`
Closes #279
=> set chatCell selection style to none

CriticalMass/RulesViewController.swift
Set BG Color for NavigationController
The Controller had a `clear` background which looks a little broken
| Before 🐛 | After 🦋 |
| --- | --- |
|<img width="575" alt="Screenshot 2020-09-09 at 09 37 54" src="https://user-images.githubusercontent.com/14075359/92569263-ae2ad600-f280-11ea-8ff7-27c9761085da.png">|<img width="575" alt="Screenshot 2020-09-09 at 09 38 57" src="https://user-images.githubusercontent.com/14075359/92569315-c1d63c80-f280-11ea-8c1e-094607b77fde.png">|
=> [RulesController] set NavigationController view backgroundColor

CriticalMapsUITests/SnapshotHelper.swift, Settings.bundle/com.mono0926.LicensePlist.latest_result.txt, Settings.bundle/com.mono0926.LicensePlist/SDWebImage.plist
executed `fastlane snapshot update` and also added updated licenses
=> Update SnapshotHelper and licenses

CHANGELOG.md, CriticalMaps.xcodeproj/project.pbxproj, CriticalMaps.xcodeproj/xcshareddata/xcschemes/CriticalMaps Simulation.xcscheme, CriticalMaps.xcodeproj/xcshareddata/xcschemes/CriticalMaps.xcscheme, CriticalMaps.xcodeproj/xcshareddata/xcschemes/CriticalMapsSnapshotTests.xcscheme, CriticalMaps.xcodeproj/xcshareddata/xcschemes/CriticalMapsTests.xcscheme, CriticalMaps.xcodeproj/xcshareddata/xcschemes/CriticalMapsUITests.xcscheme, CriticalMass/AppController.swift, CriticalMass/BlurryFullscreenOverlayView.swift, CriticalMass/CMAnnotationController.swift, CriticalMass/CMAnnotationView.swift, CriticalMass/ChatViewController.swift, CriticalMass/FontMetrics.swift, CriticalMass/Logger.swift, CriticalMass/MKMapView+Register.swift, CriticalMass/MapInfoViewController.swift, CriticalMass/MapViewController.swift, CriticalMass/NextRidesRequest.swift, CriticalMass/PathObserver.swift, CriticalMass/RatingHelper.swift, CriticalMass/RulesDetailViewController.swift, CriticalMass/RulesViewController.swift, CriticalMass/SettingsViewController.swift, CriticalMass/SocialViewController.swift, CriticalMass/Theme.swift, CriticalMass/TweetTableViewCell.swift, CriticalMass/UIView+Autolayout.swift, CriticalMass/UIViewController+Management.swift, CriticalMassTests/CMMarkerAnnotationControllerTests.swift
Bump minimum deployment target to iOS 12
As agreed upon this bumps the projects deployment target to iOS 12
=> bump deployment target to iOS 12

CriticalMass/ThemeController.swift
from white to clear
| Before 🐛 | After 🦋 |
| --- | --- |
| <img width="583" alt="Screenshot 2020-09-16 at 15 09 11" src="https://user-images.githubusercontent.com/14075359/93341682-b3fb5b00-f82e-11ea-9df5-9078b6cd7807.png"> | <img width="551" alt="Screenshot 2020-09-16 at 15 09 42" src="https://user-images.githubusercontent.com/14075359/93341680-b362c480-f82e-11ea-9932-11dd067bdaed.png"> |
=> iOS 14 fixups

CriticalMassTests/CMMarkerAnnotationControllerTests.swift
Update time intervals.
To hopefully fix flaky tests.
=> update intervals to fix flaky tests

CHANGELOG.md, CriticalMass/Feature.swift, CriticalMass/NextRidesRequest.swift
Enable **Events** feature.
Also updates `JSONDecoder` after criticalmass.in API now uses snake_case for model properties.
When COVID times started the feature was already done but we decided not to release it since gatherings of many people where not advised. Since CMs now happen in a slightly different form I think we can add that feature now.
#253 
#325
=> Enable event feature

.github/workflows/greetings.yml
Update Wording for First Issue and First PR and make it a bit more "friendly" with emojis ;) 
The comment for first issue was: `Thank you for submitting this issue' first issue`
=> Update Wording for First Issue and First PR

CHANGELOG.md, CriticalMass/ChatInputViewController.swift, CriticalMass/L10n.swift, CriticalMass/RulesViewController.swift, CriticalMass/SettingsProjectLinkTableViewCell.swift, CriticalMass/SettingsSection.swift, CriticalMass/SettingsViewController.swift, CriticalMass/TweetTableViewCell.swift, CriticalMass/de.lproj/Localizable.strings, CriticalMass/en.lproj/Localizable.strings, CriticalMass/es.lproj/Localizable.strings, CriticalMass/fr.lproj/Localizable.strings, CriticalMass/it.lproj/Localizable.strings
Improvement of VoiceControl support
Issue #263
=> Improve VoiceControl support

CriticalMass/MapViewController.swift, CriticalMass/ThemeSelectionViewController.swift
=> [FIX] Map Dark mode (missed one place)

CriticalMapsSnapshotTests/TweetTableViewCellSnapshotTests.swift, CriticalMass/FormatDisplay.swift, CriticalMass/Tweet.swift, CriticalMass/TweetTableViewCell.swift, CriticalMass/TwitterUser.swift, CriticalMass/TwitterViewController.swift, CriticalMassTests/FormatDisplayTests.swift, CriticalMassTests/TwitterManagerTests.swift
Update `Tweet` and `TwitterUser` property names
Because we should not mix up coding styles
=> update Tweet and TwitterUser property names

CriticalMass/CriticalMaps-Info.plist
=> remove icon from plist

CriticalMass/MapInfoViewController.xib
=> set container view bg color to clear

CriticalMass/CMAnnotationController.swift, CriticalMassTests/CMMarkerAnnotationControllerTests.swift, CriticalMassTests/RequestManagerTests.swift, CriticalMassTests/XCTestCase+Helper.swift
=> Fix flaky tests

CriticalMapsKit/Sources/AppFeature/AppFeatureCore.swift, CriticalMapsKit/Sources/AppFeature/AppNavigationView.swift, CriticalMapsKit/Sources/Styleguide/Colors.swift, CriticalMapsKit/Sources/Styleguide/NavigationBar.swift, CriticalMapsKit/Tests/AppFeatureTests/AppFeatureCoreTests.swift
add basic sheet navigation to present dummy views chat, rules and settings
=> add basic sheet navigation

CriticalMapsKit/Sources/AppFeature/AppNavigationView.swift, CriticalMapsKit/Sources/GuideFeature/GuideDetailView.swift, CriticalMapsKit/Sources/MapFeature/UserTrackingButton.swift
- add `showsLargeContentViewer` support for app navigation view items
- add `isModel` trait for modally presented views
closes #439
=> A11y update

CriticalMapsKit/Sources/ApiClient/Requests/Request.swift
To identify the version of the client every request will send a new field `"Client-Version"`
=> Add additional header field `Client-Version`
