criticalmaps/criticalmaps-ios

CriticalMass/PLConstants.m

`postv2` is not needed anymore.
at some point we should probably think about more meaningful routes. ;)

Switch back to api.criticalmaps.net

---

CriticalMass/RulesDetailViewController.swift

Fix issue #31 clipped images

---

CriticalMass/AppController.swift
CriticalMass/RequestManager.swift

The RequestManager was lazy initialized, which caused that it wasn't initialized before opening the chat. Removing the lazy keyword fixes that. 
Additionally, I added a request on App launch, to get data before the first timer event happens (after 12 seconds)
fixes #58

Fixed missing location data on launch

---

CriticalMass/ChatMessage.swift
CriticalMass/ChatMessageTableViewCell.swift

The [Android app uses URL encoding](https://github.com/criticalmaps/criticalmaps-android/blob/d484b4b5266fdb81b7fd04e7c03adcf8878e8fc4/app/src/main/java/de/stephanlindauer/criticalmaps/model/ChatModel.java#L42)  for messages which currently doesn't get decoded properly. 
@stephanlindauer  is there a reason for the url encoding?

Fixed decoding Android Messages

---

CHANGELOG.md
CriticalMass/ChatInputView.swift
CriticalMass/ChatViewController.swift

disables send button when the chat message textField isEmpty.
fixes #73

Empty chat input fix

---

CHANGELOG.md
CriticalMass/NetworkLayer.swift
CriticalMass/NetworkOperator.swift
CriticalMass/RequestManager.swift
CriticalMassTests/RequestManagerTests.swift

There was a possible bug that could prevent sending messages and show a loading indicator for ever if another network request is active. 
I also added a background task identifier for sending chat message to make sure that the messages get send after a user closes the app

Improved message send 

---

CriticalMass/ChatManager.swift
CriticalMass/LocationManager.swift
CriticalMass/MapViewController.swift
CriticalMass/MemoryDataStore.swift
CriticalMass/Notification+Static.swift
CriticalMass/Preferences.swift
CriticalMassTests/MemoryDataStoreTests.swift

Updates the apps Notifications to be of type `Notification` and collect all NNotifications in an extensionn to have the Strings in one place.
Follow up to the #69 PR
* collect Notifications in an extension
* update NSNotification to Notification
* adopt Notifications to new static lets

Notification Static

---

CHANGELOG.md
CriticalMass/ChatViewController.swift
CriticalMass/TextFieldWithInsets.swift

Currently, the keyboard is dismissed after the Chat disappeared. With this PR the we dismiss the keyboard on tapping the close button.
It also fixes #72

Chat Keyboard improvements

---

CriticalMass/ChatInputView.swift
CriticalMass/ChatViewController.swift
CriticalMass/NavigationOverlayViewController.swift
CriticalMass/TextFieldWithInsets.swift
CriticalMass/ThemeController.swift
CriticalMass/ThemeDefining.swift
CriticalMassTests/ThemeControllerTests.swift

fixed:
- missing separator
- hidden by software keyboard on iPhone X devices
- missing placeholder after editing

Chat input view fixes

---

CHANGELOG.md
CriticalMaps.xcodeproj/project.pbxproj
CriticalMass/Logger.swift
CriticalMass/RequestManager.swift
CriticalMassTests/RequestManagerTests.swift

During yesterdays ride, my app was often stuck and didn't received any updates. Especially after coming back from background. 
I found a bug that we never set hasActiveRequests to false after a failed requests which could have caused that issue. The updated test case handles this case. 
I added some OSLogs for easier debugging in the future

Fixed missing update after failed request

---

CriticalMass/MapViewController.swift

Adds mapOverlays aboveRoads instead of aboveLabels so that
becomes

DarkModelOverlayFix

---

CHANGELOG.md
CriticalMass/BlurryOverlayView.swift
CriticalMass/BlurryOverlayView.xib
CriticalMass/Colors.swift
CriticalMass/LocationManager.swift
CriticalMass/MapViewController.swift
CriticalMass/NoContentMessageLabel.swift
CriticalMass/Notification+Static.swift
CriticalMass/Preferences.swift
CriticalMass/SettingsGithubTableViewCellTableViewCell.xib
CriticalMass/SettingsSection.swift
CriticalMass/SettingsSwitchTableViewCell.swift
CriticalMass/SettingsSwitchTableViewCell.xib
CriticalMass/SettingsViewController.swift
CriticalMass/String+LocalizedStrings.swift
CriticalMass/ThemeController.swift
CriticalMass/ThemeDefining.swift
CriticalMass/de.lproj/Localizable.strings
CriticalMass/en.lproj/Localizable.strings
CriticalMass/fr.lproj/Localizable.strings
CriticalMass/it.lproj/Localizable.strings
CriticalMassTests/ThemeControllerTests.swift

This PR adds the Observation mode (#41) and replaces the old GPS switch to disable posting updates to the backend. I also updated the UI for the No GPS overlay which no has a button that links directly to the system settings 
Light mode:
Dark mode:

Observation mode 

---

CHANGELOG.md
CriticalMaps.xcodeproj/project.pbxproj
CriticalMass/SettingsSwitchTableViewCell.xib
CriticalMass/TweetTableViewCell.swift
CriticalMass/TweetTableViewCell.xib

Fixes two dynamic type layout issues:  
👇
👇
~~- [ ] If applicable, does the PR contain enough unit / UI tests?~~
~~- [ ] If applicable, did you add a before / after screenshot of the feature?~~

Dynamic type fix

---

CHANGELOG.md
CriticalMass/AppDelegate.swift
CriticalMass/MapViewController.swift
CriticalMass/ThemeDefining.swift

Some small improvements for iOS 13 #113 
<details><summary>before</summary>
<p>
</p>
after:
</details>
It's still not perfect as the Navigationbar textColor only updates on reopening settings. We should try to adapt the new apis for iOS 13.
<details><summary>before</summary>
<p>
</p>
after:
</details>

iOS 13 improvements

---

CriticalMass/ChatManager.swift
CriticalMass/MessagesTableViewController.swift
CriticalMass/NetworkLayer.swift
CriticalMass/NetworkOperator.swift
CriticalMass/RequestManager.swift
CriticalMass/TwitterManager.swift
CriticalMassTests/TestHelper.swift
CriticalMassTests/TwitterManagerTests.swift

This PR will make error creation a little bit more verbose to make finding errors easier.
```swift
enum NetworkError: Error {
case fetchFailed(Error?)
case unknownError(message: String)
case decodingError(Error)
case encodingError(Encodable)
case noData(Error?)
case invalidResponse
}
```

Improve network error

---

CriticalMass/TweetTableViewCell.xib

Bringing the app closer to the design 🎨
**NOW**
**THEN**

update tweet cell layout

---

.travis.yml
CHANGELOG.md
CriticalMass/ThemeController.swift
CriticalMass/ThemeDefining.swift

This should fix navigationbar colors under iOS 13 which currently don't look right in XCode Sims.
Let's hope 13.1 does not change that :D
**Screenshots**

Fix NavigationBar colors under iOS 13

---

.travis.yml
CHANGELOG.md
CriticalMass/MapViewController.swift
CriticalMass/Theme.swift
CriticalMass/ThemeController.swift
CriticalMass/ThemeStore.swift
CriticalMassTests/ThemeStoreTests.swift

This PR will set the Apps Theme to the system Theme under iOS13, when the user did not set a theme before. Until the user sets a theme in the app, the systemwide userStyle will be used.

Adopt dark mode

---

CriticalMass/ManageFriendsViewController.swift

I fixed a crash that happens on selecting the settings cell + disabled row editing for settings cells as it doesn't make sense to delete the settings cells

Friends fixed crash on editing name

---

CriticalMass/AppDelegate.swift

I don't remember why I added return false here. It caused a broken setup for release builds

Fixed app did finish launching for non debug builds

---

.travis.yml
fastlane/Fastfile
fastlane/Snapfile

Travis Xcode version doesn't has the iPhone SE installed, which breaks our UITests. Removing SE from the snap file in case it's not installed fixes the issue

Fixed UITests on Travis

---

CHANGELOG.md
CriticalMass/SocialViewController.swift

Fixes #171 
This moves the call from `viewWillAppear` to `viewDidLoad`, because when you slightly pull down the modal with the swipe gesture `viewWillAppear` gets called and changes the content. Everytime the modal is presented `viewDidLoad` is called, so I think this is the better place to setup the content.

Move Chat Presentation to viewDidLoad

---

CHANGELOG.md
CriticalMass/ChatInputView.swift

* renaming for clarity
* using layout anchors
* gate send event with check if text isEmpty and does not only contain of whitespace
closes #173

Fix whitespace only chat message and rework chatInputView a little

---

CriticalMass/CriticalMaps-Info.plist

Disabling ATS can cause a rejection of Apple and should be prevented. The code was added 2015 as a fix for iOS 9. As the minimum deployment target is iOS 10 now, I think it's not needed for anything anymore. I tested the app and it looks like everything is still working.

Forbid Arbitrary Loads

---

CriticalMaps.xcodeproj/project.pbxproj
CriticalMass/AnnotationController.swift
CriticalMass/BikeAnnotationController.swift
CriticalMass/LocationProvider.swift
CriticalMass/Logger.swift
CriticalMass/MKMapView+Register.swift
CriticalMass/MapViewController.swift
CriticalMass/UIView+Autolayout.swift

I moved Annotation specific logic out of MapViewController into its own controller as the current MapView infrastructure becomes hard to maintain if we add more logic to it in the future. 
If we wanna add more annotationTypes (Friends, events etc), we'll just need to create a new `AnnotationController` subclass  and add that to `private lazy var annotationController: [AnnotationController]` and the rest should work out of the box

MapViewController Refactoring

---

CHANGELOG.md
CriticalMass/NavigationOverlayViewController.swift

Adding the tabbar traits enables some VoiceOver improvements out of the box such as quicker navigation and VoiceOver automatically announces "Button label 1 out of N" instead of of just "Button label" which is also the default behaviour of a UITabBarController.

Improved Accessibility for NavigationOverlayViewController

---

CriticalMaps.xcodeproj/project.pbxproj
CriticalMass/AppDataStore.swift
CriticalMass/ChatManager.swift
CriticalMass/Date+Additions.swift
CriticalMass/NextRideRequest.swift
CriticalMass/Preferences.swift
CriticalMass/RatingHelper.swift
CriticalMass/Theme.swift
CriticalMass/ThemeController.swift
CriticalMass/ThemeStore.swift
CriticalMass/UserDefaults+Additions.swift
CriticalMassTests/AppDataStoreTests.swift
CriticalMassTests/ChatManagerTests.swift
CriticalMassTests/DateAdditionsTests.swift
CriticalMassTests/RatingHelperTests.swift
CriticalMassTests/ThemeStoreTests.swift

What should have been a hands-on for PropertyWrappers turned out to be just a small refactoring for the use of `UserDefaults` in our app. Since they were kind of all around I wanted to centralize them and remove some boilerplate code. Using the Wrapper turned out to be not that handy with the current structure so I ended up streamlining the use of UserDefaults a bit

Add userDefaults to extension

---

.github/workflows/update_dependencies.yml
update_dependencies.sh

I added a run of Unit tests to the update dependency action so that we can make sure that the code still compiles and works™️ because PR that use `secrets.GITHUB_TOKEN` don't trigger other CI Actions. Additionally, it will trigger an swiftformat and license-plist

Run tests on weekly update dependencies

---

CriticalMaps.xcodeproj/project.pbxproj
CriticalMass/BlurryFullscreenOverlayView.swift
CriticalMass/MapViewController.swift
CriticalMass/SocialViewController.swift
Settings.bundle/com.mono0926.LicensePlist.latest_result.txt

I added `$PROJECT_FILE_PATH` to specify the the Path to Package.Swift to hopefully fix the broken path on CI #234 
There are also some changes caused by an updated SwiftFormat version

Improved license-plist config on CI

---

CriticalMaps.xcodeproj/project.pbxproj

To be able to archive the build and upload to appstore, I needed to clear the field of Code Signing Entitlements:

Fix entitlements

---

.github/workflows/main.yml
.github/workflows/update_dependencies.yml
fastlane/Fastfile

I added caching for SPM and Bundler dependencies #231 
I also removed the resolve dependency workaround from Fastlane since the new Fastlane version we are using, doesn't require the workaround anymore https://github.com/fastlane/fastlane/releases/tag/2.141.0

Added Dependency Caching on CI

---

.gitignore
CriticalMaps.xcodeproj/project.pbxproj
CriticalMaps.xcodeproj/xcshareddata/IDETemplateMacros.plist

The standard Xcode FILEHEADER is bloated, redundant and not (always) refactorsafe.
This PR adds a template for creating files in the project. 
The Header is up for discussion. First draft:
```swift
//
// Created for CriticalMaps in 2020
import Foundation
```
Also part of the PR is to remove the Class Prefix `PL` which is never used and probably a thing of the past 🦖

update fileheader comment & remove PL class prefix

---

CHANGELOG.md
CriticalMaps.xcodeproj/project.pbxproj
CriticalMass/IdentifiableAnnnotation.swift
CriticalMass/SimulationNetworkDataProvider.swift
CriticalMassTests/IdentifiableAnnotationTests.swift

I was experiencing a delay for displaying Annotations but couldn't really find the issue but I accidentally found it while debugging #228 .
Because didSet won't get called on Init we are not setting the Coordinate Attribute which is needed to display the Annotation on a Map. So we were just showing Annotations that were shown before which als results in an empty Map for (minimum) 12 seconds after launching the App.
We should probably send out a new version with this fix

Fixed delay for displaying Annotations on Map

---

.github/workflows/main.yml

I noticed that the CI sometimes fails during the checkout step (https://github.com/criticalmaps/criticalmaps-ios/actions/runs/50668185). 
Updating to v2 hopefully helps

Bumped CI checkout actions to v2

---

CriticalMaps.xcodeproj/project.pbxproj
Settings.bundle/com.mono0926.LicensePlist.latest_result.txt

I removed the duplicated Import of SDWebImage and bumped the minimum version of swift-snapshot-testing to 1.7.2 (https://github.com/pointfreeco/swift-snapshot-testing/releases/tag/1.7.2)
Compatibility with Xcode 11.4

Fixed tests build Error with Xcode 11.4

---

CriticalMass/CMAnnotationView.swift

Set CriticalMass marker annotation `animatesWhenAdded` property true
Adds a nice touch to it when the annotation is added to the map in the visible area

Animate CriticalMass Annotation when added to the map

---

CHANGELOG.md
CriticalMaps.xcodeproj/project.pbxproj
CriticalMapsSnapshotTests/TweetTableViewCellSnapshotTests.swift
CriticalMass/ChatManager.swift
CriticalMass/FormatDisplay.swift
CriticalMass/RatingHelper.swift
CriticalMass/RequestManager.swift
CriticalMass/Sequence+Additions.swift
CriticalMass/TimeTraveler.swift
CriticalMass/TweetTableViewCell.swift
CriticalMass/TwitterManager.swift
CriticalMassTests/FormatDisplayTests.swift
CriticalMassTests/NextRideManagerTests.swift
CriticalMassTests/NextRidesRequestTests.swift
CriticalMassTests/TimeTravlelerTests.swift

I added some tests and simplified some code to improve the test coverage of the project. While writing tests, I found and fixed a small bug in FormatDisplay when the difference between now and a Tweets created_date is less that 1 minute. I also removed the static date variables in DateFormatter that could end up in outdated time stamps for tweets if the app was open for a while.

Improved Code Coverage + Bug fixes

---

CHANGELOG.md
CriticalMass/MapViewController.swift

I added support for Full Page screenshots. For now, we'll just create a screenshot without any overlays (Thats the same what Apple maps does). Just that Map + Annotations. But we can also consider changing the size, removing UI or adding elements based on our needs cc. @zutrinken.
TIL there is an API to render map images  MKSnapshotter https://developer.apple.com/documentation/mapkit/mkmapsnapshotter. I decided to simply draw the view hierarchy for now, because MKSnapshotter doesn't support Annotations so we would need to add them manually to the context. But if we decide to change the aspect ratios of the screenshots (e.g. Showing a larger region, than the currently displayed region) MKSnapshotter might be useful, because it makes sure that all necessary tiles for the snapshots are …

Added support for Full Page Screenshots

---

.github/workflows/main.yml
.github/workflows/update_dependencies.yml

Somethings wrong with the SPM cache. I couldn't find an option to reset caches on CI machines... how should errors with caches be handled??? 
For example in this [job](https://github.com/criticalmaps/criticalmaps-ios/runs/597469190):
```
Run swift build
[1/29] Compiling CriticalMapsKit APIRequest.swift
<unknown>:0: error: PCH was compiled with module cache path '/Users/runner/runners/2.168.0/work/criticalmaps-ios/criticalmaps-ios/.build/x86_64-apple-macosx/debug/ModuleCache/19B30ZHLDOJUE', 
but the path is currently '/Users/runner/runners/2.169.0/work/criticalmaps-ios/criticalmaps-ios/.build/x86_64-apple-macosx/debug/ModuleCache/19B30ZHLDOJUE'
<unknown>:0: error: missing required module 'SwiftShims'
```
This [SPM job](https://github.com/criticalmaps/criticalmaps-ios/pull/285/checks?check_r …

Disable SPM Cache

---

CHANGELOG.md
CriticalMass/Feature.swift
CriticalMass/MapViewController.swift

I reintroduced a feature flag for the Events feature and disabled it for now
I could be misleading if we present user rides that don't happen. I think we should release the feature, once rides can happen again.

Disabled events feature

---

CriticalMaps.xcodeproj/project.pbxproj
CriticalMass/AlertPresenter.swift
CriticalMass/AppController.swift
CriticalMass/CMAnnotationView.swift
CriticalMass/ChatViewController.swift
CriticalMass/L10n.swift
CriticalMass/MapViewController.swift
CriticalMass/Ride.swift
CriticalMass/en.lproj/Localizable.strings

Add `UIMenu` support for iOS 13 and a `UILongPressGestureRecognizer` for < iOS13 to add some context to the Critical Mass Annotation.
* also adds an AlertPresenter to consolidate alert presenting. Please excuse cause not really part of this task
To better integrate in the OS and to add some functionality to the Event annotation

Add context menu or actionsheet to next event annotation

---

CriticalMaps.xcodeproj/project.pbxproj

Raised the deployment target of the SnapshotTests-Target to iOS 11
The deployment target of the app itself remains unchanged at 10.3
The snapshot framework we are using requires a target of at least iOS 11

Fixed SnapshotTests

---

CriticalMassTests/RequestManagerTests.swift

Disable Flaky Test which lately always fails on CI.
This test needs some investigation why it fails on CI. There is an issue to check and enable this test again #266

Disable Flaky Test and link to Issue

---

CriticalMaps.xcodeproj/project.pbxproj

This setting prevents having unintentional different indentation styles in the project.
This is especially useful when a developer (like me) defaults to indentation with tabs in Xcode [as accessibility feature](https://www.reddit.com/r/javascript/comments/c8drjo/nobody_talks_about_the_real_reason_to_use_tabs/).

Add Indentation Configuration for Xcode Project

---

CriticalMaps.xcodeproj/project.pbxproj
CriticalMapsSnapshotTests/SettingsViewControllerSnapshotTests.swift
CriticalMass/AppController.swift
CriticalMass/AppDataStore.swift
CriticalMass/ChatInputViewController.swift
CriticalMass/ChatManager.swift
CriticalMass/ChatViewController.swift
CriticalMass/LocationManager.swift
CriticalMass/MapViewController.swift
CriticalMass/NextRideManager.swift
CriticalMass/Preferences.swift
CriticalMass/RatingHelper.swift
CriticalMass/SettingsSection.swift
CriticalMass/SettingsViewController.swift
CriticalMass/ThemeController.swift
CriticalMass/ThemeStore.swift
CriticalMass/UserDefaults+Additions.swift
CriticalMassTests/AppDataStoreTests.swift
CriticalMassTests/ChatManagerTests.swift
CriticalMassTests/FriendsVerificationControllerTests.swift
CriticalMassTests/NextRideManagerTests.swift
CriticalMassTests/RatingHelperTests.swift
CriticalMassTests/ThemeStoreTests.swift

This PR is intending to cut the Stores into smaller pieces and instead of injecting or directly referencing `UserDefaults` using Protocols to define what properties are accessible from an injected resource.
The `UserDefaults` then conform to these Protocols.
* Clearer dependencies
* Removes UserDefaults from Tests

[Refactor] facade userdefaults

---

.github/workflows/greetings.yml

This will (hopefully) fix the failing greeting pipeline from [here](https://github.com/criticalmaps/criticalmaps-ios/pull/330). The reason why it failed is probably that actions from forks can't access the github actions which are configured in this repository. That's why we use this workaround on the main workflow:
```
on:
push:
branches:
- master
pull_request:
branches:
- master
```
instead of just using `on: [push]`. 
For our greetings problem it is a recommended solution to use `pull_request_target` instead of `pull_request`. 
See the discussions here: 
- https://github.com/actions/first-interaction/issues/10
- https://github.community/t/github-actions-are-severely-limited-on-prs/18179/18
The greeting for first contributors fails when they add a PR from their fork.

Fix GithubAction First Contribution from Forks

---

CriticalMass/MapViewController.swift
CriticalMass/UIApplication+Appearance.swift

Adds a BlurEffectView under the StatusBar since with the map it sometimes led to not so nice visual effects
| Before 🐛 | After 🦋 |
| --- | --- |
| <img width="659" alt="Screenshot 2020-10-06 at 12 02 29" src="https://user-images.githubusercontent.com/14075359/95199719-8f672300-07dd-11eb-8341-9059527b6d9d.png"> | <img width="659" alt="Screenshot 2020-10-06 at 12 01 35" src="https://user-images.githubusercontent.com/14075359/95199726-9130e680-07dd-11eb-8ba2-9de487d0394d.png"> |

add blureffectView on map

---

CriticalMass/MapViewController.swift

+ do not overlay map with custom tiles when > ios13
fixes custom tile overlay introduced in #336

FIX Dark mode map overlay on > iOS 13

---

CHANGELOG.md
CriticalMass/NavigationOverlayViewController.swift

Fix the bottom (y-) positioning of the NavigationOverlay 'tab/nav bar'.
Alternative (suggested by issue-creator):
Which I don't think will work with the AppStore guidelines...
> Maybe putting it on the info section on settings would be a good option.
The **center** of the NavOverlay was set to the height of the 'tab/nav-Bar', causing a margin half the overlays height. Therefore the highest point of the overly is exactly 1.5 * the overlays height from the bottom of the screen. This was ignored when setting the `bottomContentOffset`, blocking the "Legal" button and potentially causing further problems in future updates.
Furthermore, `bottomContentOffset` takes into account `layoutMargins.bottom`. Therefore the "Legal" button was only blocked on iPhone != X. Moving the NavOverlay a bit …

fix MavView `bottomContentOffset` (for legal info)

---

CriticalMass/MapInfoViewController.swift

Add constant `15` to topAnchor of the map info view
After adding #340 the map info view needs a little bit more headroom
| Before 🐛 | After 🦋 |
| --- | --- |
| <img width="579" alt="Screenshot 2020-10-16 at 17 48 39" src="https://user-images.githubusercontent.com/14075359/96280434-40d53800-0fd8-11eb-87ba-6dee7a93aa28.png"> | <img width="697" alt="Screenshot 2020-10-16 at 17 48 57" src="https://user-images.githubusercontent.com/14075359/96280418-3b77ed80-0fd8-11eb-8371-b1e3dd04c367.png"> |

[FIX] MapInfoView topAnchor

---

CriticalMass/LocationManager.swift

Set `showsBackgroundLocationIndicator` to true
To be more transparent to users
https://developer.apple.com/documentation/corelocation/cllocationmanager/2923541-showsbackgroundlocationindicator

display background location indicator

---

CHANGELOG.md
CriticalMass/BikeAnnotationView.swift

Adapt the Bike Annotation Size to be equal the sizes in Maps. All Dynamic Type Sizes are now supported and you can test this in Xcode with the Environment Overrides Menu by activating Dynamic Type.
Currently, there are some jumps in the size when the dynamic type gets higher. 
Sadly Github doesn't support videos in PR descriptions, so here are some example Screenshots.
| Before L 🐛 | After L 🦋 |
| --- | --- |
| <img width="754" alt="Screen Shot 2020-12-06 at 15 25 34" src="https://user-images.githubusercontent.com/26111180/101282781-4cbec880-37d7-11eb-9820-cbbf5fd021b1.png"> | <img width="766" alt="Screen Shot 2020-12-06 at 15 24 41" src="https://user-images.githubusercontent.com/26111180/101282766-331d8100-37d7-11eb-9057-53fe9d7341f5.png"> |
| Before XL 🐛 | After XL 🦋 |
| --- | --- |
| …

Adapt BikeAnnotationSize to equal the Sizes in Maps

---

CHANGELOG.md
CriticalMass/MapViewController.swift

Setting `overrideUserInterfaceStyle = .unspecified` "causes the view controller to inherit the interface style from the system or a parent view controller" which is exactly what we want in this case.
Tested the feature on iOS 14.2 and iOS 12.1 in simulator.
Fixes #379 and simplifies the logic a lot.

Fix Switching Appearance Settings and using `.system`

---

.github/dependabot.yml

This changes the schedule to monthly for all dependabot updates. This also removes some unhelpful comments.
I think monthly updates are fine enough.

Update Schedule of Dependabot

---

CHANGELOG.md
CriticalMass/NextRideManager.swift
CriticalMass/Ride.swift
CriticalMassTests/NextRideManagerTests.swift
CriticalMassTests/NextRidesRequestTests.swift

* Add `enabled` parameter to ride object. https://github.com/criticalmass-one/criticalmass-in/blob/19251cdcea9db966a5e411c8a058d7a04aa92c7f/src/Entity/Ride.php#L315
* Make RideManager check if the "nextRide" is enabled and otherwise do not save it as the next ride
* save nextRide it is enabled but does not have an eventType set. Might happen since the API is not 💯
* we do not want to show cancelled events.
* rides without eventType were showing on the map as an annotation and also the event banner is shown but tapping on it did not focus the next event since it was not set in the 'RideManager'. Coming back to the codebase after 3 months (even 3 months of not coding this feels weird... but 🤷‍♂️)

[Events feature] add ride `enabled` parameter

---

CHANGELOG.md
CriticalMass/CriticalMassAnnotation.swift
CriticalMass/MapViewController.swift
CriticalMass/Ride.swift
CriticalMassTests/CMMarkerAnnotationControllerTests.swift
CriticalMassTests/NextRideManagerTests.swift
CriticalMassTests/NextRidesRequestTests.swift

Set `latitude` -> [BE property](https://github.com/criticalmass-one/criticalmass-in/blob/512f411a62a8053193464b5d0a1f84abbc98eb46/src/Entity/Ride.php#L156) 
and `longitude` -> [BE property](https://github.com/criticalmass-one/criticalmass-in/blob/512f411a62a8053193464b5d0a1f84abbc98eb46/src/Entity/Ride.php#L166)
as optional properties
By now most properties are optional and I even thought about making all of them optionals. If anyone is reviewing please check with the [Ride.php](https://github.com/criticalmass-one/criticalmass-in/blob/master/src/Entity/Ride.php) if maybe another of the properties in `Ride.swift` has to be optional... But I think I got them now. 👀
Although I never any crash reports I think this should solve the issue of a crashing app 🤞

🚑 Ride type fixes that hopefully end the crashes

---

CHANGELOG.md
CriticalMass/ChatMessage.swift
CriticalMassTests/MessagesDefaultDataSourceTests.swift
CriticalMassTests/MessagesDiffableDataSourceTests.swift

Add an id to chat message object for diffing.
The app crashed due to identical chat messages from the API. 
<details><summary>Xcode console log</summary>
<p>
```
2021-06-25 19:52:20.801165+0200 CriticalMaps[9495:418688] *** Assertion failure in -[_UIDiffableDataSourceUpdate initWithIdentifiers:sectionIdentifiers:action:desinationIdentifier:relativePosition:destinationIsSection:], _UIDiffableDataSourceHelpers.m:276
2021-06-25 19:52:20.833125+0200 CriticalMaps[9495:418688] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Fatal: supplied item identifiers are not unique.'
```
</p>
</details>
<details><summary>API Response</summary>
<p>
```json
"chatMessages": {
"0f54d5029bc247adbb7ec91c5055d603": {
"message": "komme voraussichtlich 33 nach 7 in BS …
```

[Fix Chat] - Add internal id to Chatmessage object

---

App/iOS App/Info.plist
CriticalMaps.xcodeproj/project.pbxproj

Due to the new project structure the app needs to mirror the Packages `L10n` module language content to enable regional localizations.

[🌏 Fix] Mirror L10n module strings files in app target to enable Localizations

---

CHANGELOG.md
CriticalMaps.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
CriticalMapsKit/Package.swift
CriticalMapsKit/Sources/AppFeature/AppFeatureCore.swift
CriticalMapsKit/Sources/AppFeature/AppView.swift
CriticalMapsKit/Sources/L10n/L10n.swift
CriticalMapsKit/Sources/L10n/Resources/de.lproj/Localizable.strings
CriticalMapsKit/Sources/L10n/Resources/en.lproj/Localizable.strings
CriticalMapsKit/Sources/L10n/Resources/es.lproj/Localizable.strings
CriticalMapsKit/Sources/L10n/Resources/fr.lproj/Localizable.strings
CriticalMapsKit/Sources/L10n/Resources/it.lproj/Localizable.strings
CriticalMapsKit/Sources/MapFeature/MapFeatureCore.swift
CriticalMapsKit/Sources/MapFeature/MapFeatureView.swift
CriticalMapsKit/Sources/MapFeature/MapOverlayView.swift
CriticalMapsKit/Sources/MapFeature/MapView.swift
CriticalMapsKit/Sources/NextRideFeature/CriticalMassAnnotation.swift
CriticalMapsKit/Sources/NextRideFeature/NextRideCore.swift
CriticalMapsKit/Sources/SettingsFeature/Resources/Acknowledgements.plist
CriticalMapsKit/Sources/SharedModels/NextRideFeature/Ride.swift
CriticalMapsKit/Sources/Styleguide/Images.swift
CriticalMapsKit/Tests/AppFeatureTests/AppFeatureCoreTests.swift
CriticalMapsKit/Tests/MapFeatureTests/MapFeatureCoreTests.swift
CriticalMapsKit/Tests/NextRideFeatureTests/NextRideCoreTests.swift

A user can now view all upcoming events from a list. The events will also be visible on the map. 
Some users requested the feature and I also thought about it but didn't found the time.

Add all upcoming ride events list

---

Gemfile.lock

This PR runs `bundle lock --add-platform x86_64-darwin-20` and tries to fix testing.
A failed log says:
```
Your bundle only supports platforms ["arm64-darwin-20", "universal-darwin-21",
"x86_64-darwin-19"] but your local platform is x86_64-darwin-20. Add the current
platform to the lockfile with `bundle lock --add-platform x86_64-darwin-20` and
try again.
```
https://github.com/criticalmaps/criticalmaps-ios/actions/runs/4791748214/jobs/8526593053?pr=469

Fix testing

---

CriticalMapsKit/Package.swift

This PR replaces `package(name:url:_:)` in the package manifest with `package(url:_:)`.
`package(name:url:_:)` is deprecated in SwiftPM 5.7.
- https://developer.apple.com/documentation/packagedescription/package/dependency/package(name:url:_:)-nqbk

Replace a deprecated method

---

CriticalMapsKit/Sources/ChatFeature/ChatInputCore.swift
CriticalMapsKit/Sources/SharedModels/AppearanceSettings.swift

This PR replaces `@BindableState` with `@BindingState`.
`@BindableState` is deprecated in the current TCA.
- https://github.com/pointfreeco/swift-composable-architecture/blob/bb384617d992b54f749af76b21c79e1bd6004e5a/Sources/ComposableArchitecture/Documentation.docc/Extensions/Deprecations/SwiftUIDeprecations.md#bindablestate

Replace a deprecated property wrapper

---

CriticalMapsKit/Sources/AppFeature/RequestTimerCore.swift

I set the `/locations`-cache TTL to 60 seconds so pulling more often doesn't really give any benefit anymore.
Not sure if this effects the frequency of pulling messages as well. If it does, please only pull that endpoint when the view is open (through a refresh button for example and at an interval that is paused once view is closed).

Set lower frequency for getting data from server

---

CriticalMapsKit/Sources/ApiClient/Requests/SendLocationPostBody.swift
CriticalMapsKit/Sources/SharedModels/Location.swift

Backend expects `latitude` and `longitude` to be formatted

Fix for `coordinate` encoding

---

CriticalMapsKit/Sources/MapFeature/MapFeatureCore.swift

Update Location Features `distanceFilter` to only publish a new location if users have moved 200 metres
To reduce sending locations too often.
For a ride of 20km it means: 
20.000 / 200 = 100 updates for a user per ride
There is some uncertainty around gps position since it might jump a bit where there maybe a timer would be the better option.

increase distance filter location update

---

CriticalMapsKit/Sources/Helpers/ContentState.swift
CriticalMapsKit/Tests/ChatFeatureTests/ChatFeatureCoreTests.swift

- return elements on `ContentState` also for `loading` case
The chat view was blinking for a short while when loading items and showing the `emptystate`.

Return `elements` for `ContentState.loading` to prevent blinking

---

CriticalMaps.xcodeproj/project.pbxproj
CriticalMapsKit/.swiftpm/xcode/xcshareddata/xcschemes/NextRideFeatureTests.xcscheme
CriticalMapsKit/Sources/Helpers/DateFormatter+Additions.swift
CriticalMapsKit/Sources/Helpers/Timezone+Extras.swift
CriticalMapsKit/Sources/NextRideFeature/NextRideCore.swift
CriticalMapsKit/Tests/NextRideFeatureTests/NextRideCoreTests.swift
CriticalMapsKit/Tests/NextRideFeatureTests/RideTests.swift
LisbonPortugal.gpx
Testplans/NextRideFeatureTests.xctestplan
Testplans/SnapshotTests.xctestplan
Testplans/UnitTests.xctestplan

It was assumed by the formatter that rides are only in german timezone which led to wrongly displayed starting times for other timezones.
- set `timeZone` on Ride timeformatter
I set this argument for the TimeZone
and used Lisbon coordinates `lat: 38,7223` `long: -9,1393`
```json
[
{
"id": 19038,
"title": "Massa Crítica Lisboa Março",
"date_time": 1711731600, // 👈
"location": "Pca Marques de de Pombal",
"latitude": 38.725715191988,
"longitude": -9.1504212236032,
"enabled": true,
"ride_type": "CRITICAL_MASS"
}
]
```

Add timezone to dateformatter

---

CHANGELOG.md
CriticalMaps.xcodeproj/project.pbxproj
CriticalMapsKit/Package.swift
CriticalMapsKit/Sources/AppFeature/AppFeature.swift
CriticalMapsKit/Sources/AppFeature/AppView.swift
CriticalMapsKit/Sources/AppFeature/RideEventView.swift
CriticalMapsKit/Sources/AppIntentFeature/CriticalMapsShortcuts.swift
CriticalMapsKit/Sources/AppIntentFeature/Localizable.xcstrings
CriticalMapsKit/Sources/AppIntentFeature/ObservationModeIntent.swift
CriticalMapsKit/Sources/AppIntentFeature/README.md
CriticalMapsKit/Sources/L10n/Generated/L10n.swift
CriticalMapsKit/Sources/L10n/Resources/de.lproj/Localizable.strings
CriticalMapsKit/Sources/L10n/Resources/en.lproj/Localizable.strings
CriticalMapsKit/Sources/L10n/Resources/es.lproj/Localizable.strings
CriticalMapsKit/Sources/L10n/Resources/fr.lproj/Localizable.strings
CriticalMapsKit/Sources/L10n/Resources/it.lproj/Localizable.strings
CriticalMapsKit/Sources/SharedModels/API/Coordinate.swift
CriticalMapsKit/Tests/AppFeatureTests/AppFeatureFeatureTests.swift
CriticalMapsKit/Tests/HelperTests/CoordinateFormattingTests.swift
CriticalMapsKit/Tests/NextRideFeatureTests/Mocks/CoordinateTestData.swift
iOS/App.swift
iOS/Info.plist

To increase the privacy of the app so that it is not accidentally tracking your location from places you do not want to share, this feature introduces a way to set the observation mode from the shortcuts app and also it can be enabled/disabled via Siri when saying one of the following:
| Siri commands |
|--------|
| Enable observation mode in Critical Maps |
| Turn on observation mode in Critical Maps |
| Disable observation mode in Critical Maps |
| Turn off observation mode in Critical Maps |
| Toggle observation mode in Critical Maps | 
https://github.com/user-attachments/assets/b2dee06d-bb66-494e-bf13-11d8a5dcd7b2

Add `AppIntent` feature
